### ISSUE TITLE
Status Reports

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#122]
As we have discussed, I prepared a `Status Report` about our [meetings](https://github.com/bounswe/bounswe2018group9/wiki/Status-Report-%231-Meetings). I would like to know your ideas about the scheme of the report and I would like to know if you think status reports will be beneficial or not. I certainly think preparing reports in reflective, thoughtful manner will give us some perspective and clarity going forward.

As you all know, we have a final deliverable assigned by **The Boss** called `Milestone Report Criteria`. I think we can integrate this report into our live `Wiki` system where we can update (add more reviews and reports) it constantly to follow dynamic nature of the agile development and where we can create linkage with related documents to prepare more interactive, lively and understandable document. 

If we agree on the ideas here, I will contact with **The Boss** to ask whether it is possible for us to develop `Milestone Report Criteria` on our `Wiki`. Furthermore, If we decide on the nature of `Status Report`s, we can separate the division of review labor among ourself on this post.

---

Could you please add the status reports you're working here for tracking purposes?
- [x] [Meetings](https://github.com/bounswe/bounswe2018group9/wiki/Status-Report-%231-Meetings), @okyksl
- [x] [Repository Overview](https://github.com/bounswe/bounswe2018group9/wiki/Status-Report-%231-Repository-Overview), @gumityolcu
- [x] [Planning](https://github.com/bounswe/bounswe2018group9/wiki/Status-Report-%231-Planning), @gumityolcu
- [x] [Requirements Analysis](https://github.com/bounswe/bounswe2018group9/wiki/Status-Report-%231-Requirements-Analysis), @serkan-ozel-2015400123
- [x] [User - View Analysis](https://github.com/bounswe/bounswe2018group9/wiki/Status-Report-%231-User-View-Analysis), @didemongu
- [ ] [System Design](https://github.com/bounswe/bounswe2018group9/wiki/Status-Report-%231-System-Design) 
- [x] [Acceptance Testing](https://github.com/bounswe/bounswe2018group9/wiki/Status-Report-%231-Acceptance-Testing), @byklyci
- [x] [Twitter API](https://github.com/bounswe/bounswe2018group9/wiki/Status-Report-%231-Twitter-API), @kemaltulum

**Comment by gumityolcu** [comment]
**About the general scheme of Milestone Review Reports :** I think the structure of the document is great. It captures the current state of the deliverables, what mistakes we made and what we should do not to make them again. Great work!

**About division of labor for the Milestone Review Reports :** We have always adopted a mindset such that everyone is welcome to contribute to any task of the project. The way I felt it, the task assignments we established in the meetings were more like guidelines than strict limitations on how each member will contribute. I think this final milestone and tasks associated with it should be even less strict. This is because, for each milestone, everyone was assigned some tasks corresponding to different deliverables of that milestone. Therefore, I believe -especially for the **Difficulties** part of the report- everyone will have some material to contribute to each of the reports. I mean, I am not against seperating the tasks but I think this seperation should be viewed even less strict than the assignments made in the meetings.

Also, for the milestone associated with the Twitter API, everyone should write a summary of the coding work they have done, according to the milestone report criteria shared by the boss on Piazza. Thus, we shouldn't assign this particular milestone report to anyone, it should be fully collaborative.

**Comment by serkan-ozel-2015400123** [comment]
I think the report you wrote is good for reviewing the weeks, what we have done and forming the homework easily

**Comment by gumityolcu** [comment]
Guys I'd like to take Milestone 3(Planning) Review Report. As I said, feel free to contribute. I will add the link to the review page once I finish reflecting and other matters and start it

**Comment by didemongu** [comment]
I will take milestone 4 (user-view anaylsis) review report.

**Comment by serkan-ozel-2015400123** [comment]
Will we write 9 milestones and final milestone in the form you specified @okyksl right?

**Comment by serkan-ozel-2015400123** [comment]
And requirement analysis was our second milestone right? I can take it

**Comment by serkan-ozel-2015400123** [comment]
Also do not forget our first requirements milestone 0: set up repository
Are we doing revising on milestones? Am I right? @okyksl

**Comment by serkan-ozel-2015400123** [comment]
Why there are two milestone 2s? [first](https://github.com/bounswe/bounswe2018group9/wiki/Milestone-%232-Initialization) 
[second](https://github.com/bounswe/bounswe2018group9/wiki/Milestone-%232---Project-Planning)

**Comment by okyksl** [comment]
@serkan-ozel-2015400123 I think we revised the milestone structure completely like one or two months ago. You can checkout the latest version of the milestones from [Project Plan](https://github.com/bounswe/bounswe2018group9/wiki/Project-Plan). We have a complete review report on the [Milestone #1](https://github.com/bounswe/bounswe2018group9/wiki/Milestone-%231) which you can checkout. I think `Milestone #0` you are referring to is now included in `Milestone #2`. As you noted, some of the milestone pages are in clash with the older milestone pages. I will try to fix that as soon as possible. We are going to write milestones that we had worked on so far, so I would say  from `Milestone #1` to `Milestone #6` and possibly `Milestone #9`. Since they are almost one-to-one in match with what **The Boss** wants from `Milestone Report` and we could easy integrate our review reports into the final `Milestone Report`.

**Comment by byklyci** [comment]
This evening ı will handle the Milestone 6 which include Acceptance Tests.

**Comment by gumityolcu** [comment]
I am taking Milestone #2, I believe it will be complete in a little time.

**Comment by okyksl** [comment]
As you know, we couldn't finalized our process of status reports last semester as we wished. I see that we have an account of our project in May, 2018 which provides some insight into our processes and critical mistakes. I think we all can learn and benefit by reading them. You can checkout all the reports [here](https://github.com/bounswe/bounswe2018group9/wiki/Status-Reports). I'm closing all the issues related: #123, #124, #127, #131, #132, #133, #135.
