### ISSUE TITLE
Some revisions about class diagram

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#140]
Class diagram is very good showing every detail **except constructors**, why **classes** are very short and don't have getter setters?

Also, between annotation and event class the number are **in reverse order** its 0*... 1 but it should be  1...0*, **this is also true between tag and event, vote and event, comment and event  classes**

Another point, why events have type, attendence etc. **as a class** instead of just a **field**. They have only one field and a getter and a settter, **and, one to one corresponce** that is its like a field?

**Comment by nazmicancalik** [comment]
@serkan-ozel-2015400123 
You are right on some points, let me enumerate
1. As far as I see, classes have getters and setters.
2. During preparation of class diagrams a mistake could be made, we can change the order of relation multiplicities. You are right. 
3. That's because they are seperate entities and they will have tables in the database when we designed them. For instance **types, comments, votes etc**. I'm not sure about the attendance. It may have one to one correspondence as you said.
I hope, this answers some of your questions, but let's focus more on Sequence Diagrams

**Comment by gumityolcu** [comment]
@nazmicancalik @serkan-ozel-2015400123 Guys, we have decided to revise the requirements, which affects virtually everything we have done this semester. Anyways, we will have to revise everything after revisin the requirements so any revisions made on class diagrams now could be a waste of time in the end. I propose raising this issue after requirements are dealt with.

**Comment by okyksl** [comment]
I think we need to have a session to become familiar with the design we made and later, another session to revise the design. For now, I don't think we can follow this issue.
