### ISSUE TITLE
Work Breakdown

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#148]
We have to breakdown the work to understand the route ahead and plan our project. If we would like to have a working, trackable and useful project plan we need enough details and also meaningful organization of the tasks. We need an initial study to determine the main tasks and possibly some details of these tasks.

@akaogluozgur @kemaltulum @nazmicancalik can you prestudy the areas you are in charge? And then, let's organize a meeting where we can put altogether which **_includes free cakes and drinks_**. After the study, I will handle the prioritization and division of the labor through the project.

Whole @bounswe/bounswe2018group9 and @mericturan, @uskudarli are also invited to study and meeting.

**Comment by nazmicancalik** [comment]
Okay, I will gladly try to explain the workflow that I have in my mind for the __backend__.
As far as I know;

* We should first refine our class diagram so that we would know the data models.
* After deciding on the data models we should create our API Design. Which includes the endpoints that needs to be created.
* After that we will distribute the endpoints to implement among ourselves as backend team.
* Implementation of the endpoints. (This part is the biggest part, architecture of backend structure will be discussed with backend team: Basic conventions for an endpoint, manipulation of data etc. )
* Authentication, locking the endpoints.
* Deployment to real server. (This could be done earlier too, we have to discuss with the frontend team.)
* Fin

I will create the first issues for the backend team so that we can have a kickstart.

**Comment by kemaltulum** [comment]
My field is about frontend and Ionic.

For frontend,
* Project setup, integration with backend
* Training of frontend team
* Decide the general structure of the web site, which tabs or parts will exist
* The code structure to support annotations
* Design issues (color, font, harmony etc.)
* Implementation of Angular components
* The synchronization between front end and backed in terms of data structures like Person, Car
* Deployment

For Ionic,
Details will be more clear soon, I think.

**Comment by okyksl** [comment]
Thanks for your feedbacks @nazmicancalik @kemaltulum. I further studied the main tasks and specifics ahead and, produced a high-level plan. You can follow-up #156 to review the plan.
