### ISSUE TITLE
Continuous Code Review

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#178]
Should we start to utilize some sort of **code review** tool to preserve consistency and coherence in our development code such as [SonarCloud](https://sonarcloud.io/about)?

**Comment by okyksl** [comment]
I integrated `Codacy` into our repository. I hope it will increase our code quality immediately.

**Comment by gumityolcu** [comment]
It looks to be working great with the PRs. Thank you, we can discuss about it after using it for a while in one of the meetings.

**Comment by okyksl** [comment]
@nazmicancalik a question: _Single quote_ for backend-js files or _double quote_?
@kemaltulum same question for the frontend-ts files.

**Comment by gumityolcu** [comment]
@okyksl @nazmicancalik 

I personally use single quotes for short, inline strings like JSON variables, endpoint names etc. I use double quotes for strings that are sentences as in error messages. If you think we should choose one for all strings, I would vote for single quotes since I find them more readable. Anyways, it is not a catastrophe for me if we use double quotes neither :laughing:

**Comment by serkan-ozel-2015400123** [comment]
@gumityolcu About quotes: I used single quotes and request failed, then used double quotes request was successful today. Do you know why? Also in postman this was the case.

**Comment by okyksl** [comment]
Our rules are written [here](https://github.com/bounswe/bounswe2018group9/blob/master/frontend/tslint.json). When this is not in the `master`, `Codacy` utilizes default options which includes **double quotes**.
