### ISSUE TITLE
Event Collection Pagination

### ISSUE THREAD

**Issue by nazmicancalik** [bounswe/bounswe2018group9#185]
We need to return limited amount of events to the frontend when an api call is made to event list endpoint. You need to check the concept of pagination. You can  refer here : https://stackoverflow.com/questions/45328393/how-to-do-pagination-in-nodejsexpressmongodb

We can always get in touch to solve this issue @gumityolcu

**Comment by gumityolcu** [comment]
On it. Thanks :+1:

**Comment by gumityolcu** [comment]
I finished the task.

I used the 'mongoose-paginate' package. Currently, GET '/api/events' endpoint needs 2 URL parameters: skip and limit. GET '/api/events/getEventbyOwner' needs 3 parameters: id, skip and limit.

In both cases, if skip is omitted, it is assumed 0, if limit is omitted it is assumed 10. If id is omitted and error message is sent back.

I opened a PR, please give your review and feedback there. I am closing the issue since it is very close to being finished.

**Comment by okyksl** [comment]
@gumityolcu thank you for your consistent effort and progress.

**Comment by gumityolcu** [comment]
@okyksl Thank you too mate, you gotta do what you gotta do :laughing:
