### ISSUE TITLE
Backend: Annotation Data Structures 

### ISSUE THREAD

**Issue by nazmicancalik** [bounswe/bounswe2018group9#245]
We need to create the database models and endpoints for the annotations. The data models are specified in the following address: https://www.w3.org/TR/annotation-model/

**Comment by gumityolcu** [comment]
On it

**Comment by gumityolcu** [comment]
You can check the branch feature/backend/annotations to follow the progress.

**Comment by gumityolcu** [comment]
@nazmicancalik @okyksl @akaogluozgur @serkan-ozel-2015400123 

Guys, I have made some changes in the data model, which needs explanation. I believe we are facing a major design choice here and I don't want to take this much initiative and work hours on the endpoints only to realize the data model is crooked or the choice I have made is a wrong one.

I will try to explain the situation to you here so that you don't have to dive into the documentation and the code. Don't hesitate to do so if you wish though :innocent:  

We have 2 issues:

1- We need to allow for multiple types of targets and selectors. This means the "target" field in the annotation data model should be flexible such that it can be a simple string or an object containing "source" and "selector" fields which means it is a SpecificResource.
(Currently my solution to this problem is that we only allow SpecificResources :laughing: )

 2- If we are working with a SpecificResource, we must allow the selector field to be compatible with different selectors. Here are some basic examples of selectors that we are thinking about implementing:
    "selector": {
      "type": "FragmentSelector",
      "conformsTo": "http://www.w3.org/TR/media-frags/",
      "value": "t=30,60"
    }

    "selector": {
      "type": "XPathSelector",
      "value": "/html/body/p[2]/table/tr[2]/td[3]/span"
    }

    "selector": {
      "type": "TextPositionSelector",
      "start": 412,
      "end": 795
    }

(Currently, I solved the problem by including **all** fields with the 'type' field being the only required field. This implies that validation will be done by hand in the POST endpoint. Personally, I am OK with coding this but I am sure this is the worst of practices.)

I researched on the net for solutions. I have read about using Schema.Types.Mixed and discriminators. These didn't seem easier nor applicable without other problems to our project.

I am quite confused. Please share your considerations.

**Comment by gumityolcu** [comment]
@nazmicancalik @okyksl @akaogluozgur @srknzl @kemaltulum 

Status update:

We now have the basic architecture needed to work with annotations on the backend side. I have implemented the CRUD endpoints quickly. I am planning to make a document explaining the portion of annotations that our platform supports for now and what we are planning to support.

Also, there are bugs and anomalies in the endpoints for now. For example, a PUT request with a missing field erases the related sub document. I will work on these soon.

The last version is pushed to the branch feature/backend/annotations

**Comment by okyksl** [comment]
@gumityolcu can you utilize `Postman` in _documentation_?

**Comment by gumityolcu** [comment]
@okyksl We are close to the point where we can :smile: 
Can you check my last comment on #371 and share your considerations? I think we can merge after handling the issue I explained there.

**Comment by gumityolcu** [comment]
I gave opened a PR for this. Closing issue.
