### ISSUE TITLE
Return type of getUser method in authentication service

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#247]
getUser(): User | null {
    const token = localStorage.getItem('token');
    if (token === null) return null;
    const decoded = this.jwtHelper.decodeToken(token);
    return { _id: decoded._id };
  }

Is return type is correct? It returns a object which has only attribute _id. Obviously this is not a User.

**Comment by serkan-ozel-2015400123** [comment]
I have refactored this method and I will be commiting the changes to **feature/frontend/profile-page** branch. You can see the changes made to this method there.

**Comment by okyksl** [comment]
It's actually correct @serkan-ozel-2015400123. Every **User** extends from an **Object** which includes an `_id` field. **Object** is designated to represent our common database related fields, and we have **optional** fields in all of our interfaces - both **User** and **Object** due to the possibility of **unpopulated data**.

**Comment by okyksl** [comment]
So for example, **User** object in creating a new user wouldn't have any `_id` field since it will be assigned by the **mongoose database**. However, User object that is stored in the token wouldn't have all the data as the token might return solely the `_id` field and the rest of the data can be downloaded from an **GET user api endpoint**.

We might store some basic user information with the **token** but I'm not rooting for that.

**Comment by nazmicancalik** [comment]
Are we done here? What's the status?

**Comment by serkan-ozel-2015400123** [comment]
Not smthng intesesting left from this issue
