### ISSUE TITLE
Feed Endpoint

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#268]
@nazmicancalik we also have to implement **feed data model**, right?

**Comment by nazmicancalik** [comment]
Yes, you are right @okyksl. I wouldn't call it data model because we only need to implement an endpoint that responds differently to every unique user. We need to create a feed endpoint that is filtering and sorting the events according to given statistics. 

These statistics include but not limited to: 

1. Interests of the user
2. Following friends of the user
3. Status and popularity of the events.

**Comment by okyksl** [comment]
@nazmicancalik what should we do here? Maybe a quick solution for the `Customer Meeting #2` and then we can build something better that we like?

**Comment by okyksl** [comment]
@nazmicancalik will handle this issue.
