### ISSUE TITLE
Mobile Initialization

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#294]
We have to **initialize our mobile version** of our hybrid application.

**Comment by nazmicancalik** [comment]
@kemaltulum any status updates?

**Comment by okyksl** [comment]
I have managed to setup both `iOS` & `Android` platforms for our application. We need to **test** our developed features in especially in `Android`. @dkilyas could you look at `Android` platform? I can answer any questions regarding with building and running the application.

A todo list for you:
- [ ] Build `Android` platform properly.
- [ ] Test whether our current application works **on emulator & device**.
- [ ] Report any discovered bugs and user interface problems.
- [ ] Document how to properly run the project in `Android`.

**Comment by dkilyas** [comment]
I have tested our application for both ios and android. Ios was tested on an emulator. At first glance, everything looked perfect. Sign in page came properly. Everything fit on to the screen. However, other things that are on the functionality side were poor. First of all, I tried sign in with my account. But the app alerted as 'You could not sign in because wrong email or password ...' although my email and password were correct. After failing on sign up, I tried registering. But the registration page did not load. I've waited for a long time. However, it did not load. I thought there was a problem on building and running the app. Hence, I again completely built and run the app. But the same things were there.

On the android side, I built the app. An unsigned apk was created. And I signed that apk so that it can be installed on the phone. After that, I installed the app onto my phone and tested it on my phone. But the same problems existed on the android side. This time was not in the emulator. 
The only exception was the registration page were loaded on android side. However, register functionality was not working.

**Comment by dkilyas** [comment]
Another thing that is not good from the point of view of a user was the error message that was given when I tried to register on the android side. The error message were meaningless for the user, even for a programmer.

**Comment by okyksl** [comment]
We have initialized **mobile platforms**, however there are some bugs concerning these platforms. @dkilyas can you open the related issues?
