### ISSUE TITLE
TEST Event Data Model 

### ISSUE THREAD

**Issue by byklyci** [bounswe/bounswe2018group9#301]
We need to test and review the event data model. The model need to be tested ASAP.

**Comment by okyksl** [comment]
First of all, **backend** team seems to be busy and rolling! Thanks for the effort guys @byklyci @gumityolcu @nazmicancalik @gkhntkl.

I have couple points on our new event data model:
1. Shouldn't we also need a `count` property inside the `comments`?
2. Can we also store a `parent` field inside individual comments so that we can displayed whom commented on which comment? This field can be null (in case of a **root comment**) or can be filled with an `_id` field of an **comment**.
3. We have a **requirement** that states that **comments are also votable**. It seems like this forces us into a direction where we need more abstraction in both **votes** and **comments**.
4. We can use `createdAt` / `updatedAt` fields of `mongoose` instead of `created`. You can checkout them [here](https://mongoosejs.com/docs/guide.html#timestamps). If we wish to utilize `created`, we can add `Date.now` as the default value to ensure we capture the **creation time**. Note that it may be the case that I'm mistaken about the purpose of `created` field.
5. Can you elaborate the purpose of `duration` field? I'm wondering how much can it capture our needs, if we were to utilize a **finish date** instead of duration. The field called `unit` should be better be unified and it seems to me it would be better if we completely bypass it.

**Comment by nazmicancalik** [comment]
#320

**Comment by okyksl** [comment]
@nazmicancalik, @akaogluozgur, @gumityolcu or @byklyci could you **list all the endpoints** that needs to be checked to the first comment in this issue so that we don't _miss any endpoint_.

**Comment by okyksl** [comment]
@nazmicancalik @akaogluozgur any progress here or is this already done?

**Comment by nazmicancalik** [comment]
Done. We are testing votes on #323
