### ISSUE TITLE
Annotation W3 Data Model 

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#304]
Is it reasonable to read all the document for everyone nowadays? When to read how much portion of it etc? @bounswe/bounswe2018group9

**Comment by gumityolcu** [comment]
I am reading to document in order to generate an annotation data model template for the backend part. There should be at least one person from the frontend team to read the document at least once. I believe you may skip some parts if you believe them to be not essential, without forgetting those parts exist and consulting them when necessary.

**Comment by okyksl** [comment]
@serkan-ozel-2015400123 you can checkout and skim over the document to see what is the purpose of the model and the basic structure of it. I would recommend it so that you can see why _engineers_ need **standards** and particularly what kind of standards we have in our sector.

For the implementation parts, we will handle the necessary information flow.
