### ISSUE TITLE
Merge feature/backend/annotations into staging 

### ISSUE THREAD

**Issue by srknzl** [bounswe/bounswe2018group9#373]
@gumityolcu  Can you finalize your work and merge feature/backend/annotations branch into staging so that I can test it and connect with backend during my frontend annotation experiments

**Comment by gumityolcu** [comment]
There are already 2 issues about annotations in backend. I will finalize the code the first chance I get. I will open a Pr to merge to master. We can merge to staging then. Closing issue since this is not a big issue. Can you add a comment at one of the other 2 branches? I check them after completing my work, it will remind me to merge it into staging.
