### ISSUE TITLE
Event Edit & Timeline

### ISSUE THREAD

**Issue by kemaltulum** [bounswe/bounswe2018group9#407]
I implemented event edit page.

The creator of the user can edit the event going its detail page.

In addition to this, I think, it would be good to show events created by a user on his/her timeline, which can be editable by him/her.

I am asking whether it is doable  in this limited time to provide an endpoint for giving events of a spesific user.

This endpoint is important for the functionality of timeline page.

Thanks

**Comment by okyksl** [comment]
@gumityolcu?

**Comment by gumityolcu** [comment]
Yes it is possible. I will try to handle the issue today.

**Comment by gumityolcu** [comment]
Turns out we had the endpoint but it was not up to date with the current data model. I committed the last version to staging.

Currently:
GET /api/events and point returns all events if no creator parameter is given, else it give the events of the given user.

Paging is done via query parameters skip(default: 0) and limit(default: 10).

Closing the issue.

**Comment by okyksl** [comment]
@kemaltulum does this resolve our issue completely?
