### ISSUE TITLE
What Does `Vote` Mean?

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#46]
From the description of the project we know

* Users
* Comments
* Events

should be votable. But what do we mean by `voting`?

Here is what I have in my mind:

* Users can be followed or not, and that might be considered as vote. _Verified artists_ might be votable out of 10? - I wouldn't want my verified account to be rated as 4/10!
* Comments can be liked or disliked.
* Events can be voted out of 10, so that we can see user preferences more deeply and classify events according to users' taste.

Also, out of 10 can be replaced by out of 5 star system. What do you have in mind about `voting`?

**Comment by serkan-ozel-2015400123** [comment]
@okyksl I organized requirements according what I have in my mind a couple days ago. My idea was similar to yours. Like you mentioned, I only assumed that voting for a user is to follow him. But like you also have said verified users can be rated according to their follower number or a general out of 5 or 10 rating system. It is up to us. Finally I had supposed that comments and events can only be liked or disliked. We can put also a out of 5 system to events. We may need other voices to decide.

**Comment by nazmicancalik** [comment]
Here is my thoughts about voting system: 
* I think voting verified accounts is not necessary. Once an account is verified by the system admins or editors there should be no need for voting.
* For comments we can use what 9gag and reddit use: upvote or downvote. 
   * Then according to the scores of comments in one event (thread) can determine which comments will appear up top.
* I think 5 Star system is adequate and more suitable, since we can configure it to work as a 10 point degree system by making users vote for half stars. It would be better in terms of visualization also.
* Also if you wish I can add `Users shall be able to report disturbing comments.` to the requirements analysis.

**Comment by byklyci** [comment]
_In my opinion;_
* The first thing we should look for in a voting system is voter satisfaction.
* The second way to judge a voting system is its simplicity. 
* A voting system's fairness is also important. 
The system of voting can be discuss some time later.

**Comment by gumityolcu** [comment]
I never really understood why and how users should be voted in the platform but it is a requirement that came directly from the customer. I think we should ask again and clarify because I think he meant a system different than following.

I prefer using "like/dislike" system on comments because it's simple and a comment doesn't have many qualities to be voted out of 10 or 5.

I prefer using 10 point degree system on events because it is simple but expressive. I think 5 point system doesn't give enough freedom to the voter to judge the event. 

The 2 best working voting systems I can think of are those of Yemeksepeti and IMDb, which both use out-of-10 voting system.

**Comment by okyksl** [comment]
@gumityolcu let's ask this to the customer. I think **follower count** can _kinda_ represent voting of the users.

**Comment by okyksl** [comment]
@bounswe/bounswe2018group9 did we formed a consensus here?

**Comment by serkan-ozel-2015400123** [comment]
Can we cloooooooose this ??

**Comment by okyksl** [comment]
From discussions I had peer-to-peer and also discussion we had on the meetings, I think we formed a consensus, as stated on the first comment _(with 5 star system)_, on this subject.

@serkan-ozel-2015400123 could you please update `Requirements Analysis` document reflecting the nature of the voting if there are any missing detail?
Also, can you move **1.1.6.4.2.** to the appropriate place since it does not belong to the `Events -> Voting`?
