### ISSUE TITLE
Git Command Manual

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#49]
One of the suggestions we have taken for our repository was to organize a _Git command manual_. The idea behind it was to have a short look-up reference _while using Git_. Should we document such a page or should we stick with default help document i.e `git help <command-name>`?

**Comment by akaogluozgur** [comment]
We sure need to do, I think we should assign this a person at the next meeting.

**Comment by okyksl** [comment]
@akaogluozgur added to the [Meeting #5](https://github.com/bounswe/bounswe2018group9/wiki/Meeting-%235-(05.03.2018)) agenda.

**Comment by byklyci** [comment]
Thank you @okyksl because it can became confusing sometime for us.

**Comment by kemaltulum** [comment]
@okyksl @nazmicancalik I updated assignees as you based on [Meeting 5](https://github.com/bounswe/bounswe2018group9/wiki/Meeting-%235-(05.03.2018))

**Comment by nazmicancalik** [comment]
I will create a simple git manual unlike complicated ones. However the detailed section will be added too.

**Comment by nazmicancalik** [comment]
Guys after looking at the [Learn Git](https://github.com/bounswe/bounswe2018group9/wiki/Learn-Git) tab in our wiki, I decided to leave that page as it is and create another page for our most used git commands like a git cheat sheet.
I will open a new issue for that purpose, so that you can also write what you want to see in the cheat sheet. I will add the link to the new page as soon as I am done with it.

**Comment by okyksl** [comment]
Thanks for the work @nazmicancalik!
