### ISSUE TITLE
Şeyda Karagöz - Persona and User Scenario Overview

### ISSUE THREAD

**Issue by kemaltulum** [bounswe/bounswe2018group9#59]
![seyda_karagoz](https://user-images.githubusercontent.com/14013649/36842847-0624972e-1d5e-11e8-805b-c51649fa0418.jpg)

There might be some issues on Şeyda Karagöz, even though we have a concensus on the generic features of the persona.

Let's discuss such things here

**Comment by kemaltulum** [comment]
Some details may be omitted. I think that Şeyda can just live in Yalova, not in the village of it. She doesn't have to be too poor. On the other hand, her family might not push her being farmer in this age.

My suggestions

### Goals
* She wants to be popular, appreciated by the people for her work
* She wants to make money in exchange of her work

### Frustrations
* She has no idea on how to advertise her work
* No one around her is interested in her work
* She has not enough resources showing her work by travelling and joining to exhibitions

I will have updates on User Scenario and Bio in harmony with these changes

**Comment by kemaltulum** [comment]
This is the [latest version](https://app.xtensio.com/edit/hhkyy03e) after some changes.

After finishing it up, we can export it as png to add to our wiki

**Comment by byklyci** [comment]
For our character, in my opinion, we should increase the sociality level on the motivation tag.Because she is desire to find some people and if you are a person like that you should be more social then we thought.

**Comment by serkan-ozel-2015400123** [comment]
@byklyci  Okay,changing it in that way.

**Comment by byklyci** [comment]
@serkan-ozel-2015400123 yeah it doesnt matter this can be fine as you said.

**Comment by serkan-ozel-2015400123** [comment]
I finished user scenario you can check and correct or add something more. It is on persona and I add it here also: 
One day, Şeyda was sitting at their home, she was very bored and  she was surfing on the internet. She has seen an advertisement which is about an application in which people share their cultural events and others can attend. The name of the application was "Actopus", she thought that this purple octopus could have long enough arms to bring interested people into Yalova. She thought in her mind: "I draw such good paintings that people can try to come to Yalova to see my paintings. By using this application, finally, I can make my dreams come true." Then she signed up for Actopus and create her profile. First, she chose her username :"artist_ressam". Then, she created an event about her drawings' exhibition. She set up the date and time to 2 weeks later and make it free to attend. She chose event type to be "drawing" so that people who are interested can easily find her event. Also she wrote the description of the event in a very assertive way. Moreover, she put some of images of her drawings and she annotated her images to explain the art she had made. After a week there were 10 people who are willing to attend and curious about this assertive event. Şeyda was very pleasant to see that many people in her first exhibition. People who attended her event were impressed by her talent, and because incoming people were fond of good drawings, some of them bought a few drawings from Şeyda. Şeyda asked attendees to vote her event in order to be better known and reach other people. Some of them voted her event through Actopus. Gradually, she has become one of the most known artists in social media.​

**Comment by serkan-ozel-2015400123** [comment]
What is left to do:

Acceptance Criteria will be written
Profile Page (Kemal will do)
Event Creation Page(Yusuf has done)
and feed page, home page will be edited by me today.

**Comment by okyksl** [comment]
@serkan-ozel-2015400123 will there be a section for story part - `As a ... I can ... so that ...`?

**Comment by okyksl** [comment]
@serkan-ozel-2015400123 about stories:

> * As a lazy person, I can earn money from selling drawings so that I can avoid working.
> * As a poor woman, I can use Actopus so that I can be rich by selling my drawings.

I see that you changed the character a bit after @kemaltulum's comment so that she is not anymore poor or lazy. I believe there is a strong **why? point** on _becoming more popular and earning money from her work_. I think these two statements are on the same line so why not create a new story by combining these two?

> * As an ameteur artist, I can create my account in Actopus so that I can find people who wants to attend my art exhibition.
> * As a actopus user, I can create new events so that my actual event can be seen on internet.

Again, I think these two statements are in the same line and **actopus user** is too generic, it does not define **who?** enough. I think we can also combine these two.

> * As an ameteur artist, I can find other drawings so that I can get inspired by them.

I believe this is a nice feature of our platform, slight suggestion: use _artists_ instead of _drawings_.

Great work @kemaltulum, @byklyci, @serkan-ozel-2015400123 and @gkhntkl!

**Comment by nazmicancalik** [comment]
Good work guys 👍

**Comment by serkan-ozel-2015400123** [comment]
We are done with Şeyda except profile page closingggg
