### ISSUE TITLE
Ceyda Yılmaz Beylice - Persona and User Scenario Overview

### ISSUE THREAD

**Issue by nazmicancalik** [bounswe/bounswe2018group9#61]
![iremsu](https://user-images.githubusercontent.com/25107149/36886746-e5d9e0f4-1dfe-11e8-81d0-84b669de0946.jpeg)

You can reach to the profile (user story) of a woman who finds herself in a high society environment and wants to integrate with her new group of friends [here](https://app.xtensio.com/edit/at2b4167).
In order to see/edit the document please contact me I will give you access. You can also write your ideas:
* Additions
* Deletions
* Modifications
here.

This profile is prepared solely to start the process, all things written in the user story is open to debate.
Please report your feedback, because what I have done seems so narrow to me. 
Ps: The avatar image is for prototyping only, we may have to create one avatar later.

**Comment by serkan-ozel-2015400123** [comment]
"She thinks she" 👍

**Comment by gumityolcu** [comment]
I added the first version of the scenario. It is now different than what we discussed in the meeting. We think it is a better persona this way.

**Comment by gumityolcu** [comment]
We need to change Personality and Motivation parts to complete this persona. We couldn't be sure what we are supposed to say aboıut this person's personality. I remember that @akaogluozgur could easily decide on the levels of the personality bars in the meeting. Can you give us a hand? 😄

**Comment by akaogluozgur** [comment]
@gumityolcu Of course, yes.

- She is extremely close extrovert since her motivations are meaningless without another person on the Earth.
- She is fairly close to feeling since she always acts according to the first impression about the task at hand. She never thinks about them later since she is somehow live the moment merely.
- She is slightly close to sensing but not too much because she always has both intuitions (more like prejudgements) about people but they are really shallow. Also since she lives the moments she really acts according to the sensations of hers.
- Obviously, she judges people according to how they look and their reputation. There is no time to perceive and think thoroughly about things to her.

**Comment by okyksl** [comment]
@gumityolcu @nazmicancalik great work!

* I see that `Ceyda`'s character description says: 

> She is shy and needs approval from people around her.

But if we look at the _Personality_ charts, she is an extrovert more than an introvert. According to the @akaogluozgur's comment she is also more extrovert than an introvert. When I read the bio and scenario, I felt like we have a social person with insecurities about her new environment.

Should we harmonize `Character`, `Personality` and `Motivation` sections according to the extrovert/introvert criteria?

* About the degree part, how about `Healthcare Management`?.

**Comment by gumityolcu** [comment]
@akaogluozgur  Very clear and descriptive, thanks 👍 

@okyksl  Exactly, Ceyda is shy but she doesn't have an inside world where she lives by herself, where she can be happy. Instead, she needs approval from others, the external world. If you think there is an inconsistency, we can delete the "shy" adjective and replace the sentence with "She needs approval from people around her." This seems logical and in coherence with Özgür's comments.

Healthcare Management is a good choice of degree. I think whatever works as long as it is not a field like "History of Art" or "Literature", that is a field where she needs a minimum of cultural knowledge to graduate.

About the Motivation section:

I think "Fear" and "Social" should be high because our character wants to improve her social life, that is, social life is a big deal for her. Also, she is afraid of being alienated or rejected by her friends.

"Power" might be low. This is my reasoning: our character uses our application because she feels powerless and needs help. I am not sure how logical this reasoning is 😄 

I am not really sure what "Incentive" and "Growth" parts mean, maybe we can change them or look at our other personas.

**Comment by okyksl** [comment]
About **Motivation** part:

* I agree with **Fear** and **Social** motivations.
* I though of **Power** as social power among her friends but your reasoning seems more suited to `Ceyda` since she is just trying to get used to her new environment.
* I think **Growth** is related with _personal development_, I'm afraid `Ceyda` has nothing to do with **Growth**.
* I think she has legitimate **Incentive** to use this application since she needs to change her interaction with new social circle she is in.

About **Character** part:

How about _insecure_ instead of _shy_?

**Comment by gumityolcu** [comment]
@okyksl Insecure describes her better. In fact she is not shy, a shy person would not be this eager to be popular.

We made the last touches on the personality traits and added 2 acceptance criteria, I think our user story is done.

I am closing the issue.
